### ISSUE TITLE
Bestbuy

### ISSUE THREAD

**Issue by dawnerd** [duffn/dumb-password-rules#11]
You can change your password to be anything (Excellent!) but when you try to log back in you're locked out. Seems to happen when a password is really long.

I have a 64 character password containing symbols and all the fun stuff generated through 1pass. On login: `Sorry, a problem occurred during sign in. Please try again.`

**Comment by duffn** [comment]
Nice. You can create whatever password you like, but you can never login again.

If you can grab a screenshot, let's get it in here.

**Comment by dawnerd** [comment]
![image](https://cloud.githubusercontent.com/assets/24781/20899736/8249af24-bae0-11e6-9b2b-05bfa0b06b90.png)
![image](https://cloud.githubusercontent.com/assets/24781/20899804/c537226c-bae0-11e6-86ca-13b824ec62ee.png)

**Comment by duffn** [comment]
https://github.com/duffn/dumb-password-rules/pull/24
