### ISSUE TITLE
Consistent image sizes to make it easier to view

### ISSUE THREAD

**Issue by nitrocode** [duffn/dumb-password-rules#112]
Some images may have to be cropped but many could be resized using [html](https://gist.github.com/uupaa/f77d2bcf4dc7a294d109#gistcomment-1880104). This would make it a lot easier for mobile viewers. 

    <img src="url" alt="alt text" width="whatever" height="whatever">

**Comment by duffn** [comment]
Excellent idea.

**Comment by viperx77** [comment]
Might be a problem due to your choice of reStructureText for the markup. See https://github.com/github/markup/issues/295

**Comment by duffn** [comment]
This was done with the new static site https://github.com/duffn/dumb-password-rules/pull/443
