### ISSUE TITLE
Extended with dumb-email-rules or to dumb-form-rules?

### ISSUE THREAD

**Issue by nitrocode** [duffn/dumb-password-rules#113]
I noticed https://github.com/duffn/dumb-password-rules/issues/70 for bad username rules. Would you be interested in websites with bad email rules too?

The one rule that annoys me with email is when they prevent you from signing up using the plus character. e.g. you can filter your email better in gmail if you add a + and then some string to your email like `bobthebuilder+github@gmail.com` will get sent to `bobthebuilder@gmail.com` but lots of websites will prevent the plus character.

If you're willing to extend it to bad emails, it may not be too much of a stretch to extend this as bad-form-rules or bad-login-rules to keep it more generic.

**Comment by duffn** [comment]
I would certainly consider dumb email/username rules acceptable as well.

**Comment by duffn** [comment]
Please feel free to open any PRs you may have with dumb password/username/email validation/etc rules!
