### ISSUE TITLE
Platforms other than websites?

### ISSUE THREAD

**Issue by xorhash** [duffn/dumb-password-rules#168]
The Internet is not only the web (even though there's a *lot* of web). I've got an offender they might warrant an entry, even though they're not a website: QuakeNet's IRC services.

Maximum of *10* characters. Bonus points: stored in plaintext!

- https://github.com/quakenet/newserv/blob/master/chanserv/chanserv.h#L63 (defines `PASSLEN` to 10)
- https://github.com/quakenet/newserv/blob/master/chanserv/chanserv.h#L586 (declares `reguser.password` as `char password[PASSLEN+1]`)
- https://github.com/quakenet/newserv/blob/master/chanserv/chanservuser.c#L559-L566 (password check function is `strncmp()` => plaintext password)

Not a website though, should I add this? If not, how should I make the relevant screenshots?

**Comment by duffn** [comment]
I guess the tagline does say "sites" but I'm okay with this if you want to submit a PR.

**Comment by duffn** [comment]
Anyone should feel free to submit PRs for any dumb sites/usernames/IRC service/etc/etc and I'll review them. A dumb rule is a dumb rule, no matter where it is.
