### ISSUE TITLE
Add NASA's Earthdata registration

### ISSUE THREAD

**Issue by Zwork101** [duffn/dumb-password-rules#255]
I'm making this issue now, so I can make a PR later if this looks good. These requirements are over the top, especially the special character one. https://urs.earthdata.nasa.gov/users/new

![image](https://user-images.githubusercontent.com/25652654/65448452-d1a60800-de06-11e9-8085-f399303e4ac6.png)

**Comment by duffn** [comment]
Thanks, that's definitely worth a PR.
