### ISSUE TITLE
PayPal screenshot

### ISSUE THREAD

**Issue by onebree** [duffn/dumb-password-rules#26]
It looks like the new password, and the confirmation fields do not have the same password.

The new password has one more dot than the confirmation. I would try submitting matching new/confirmation password again and see if the error continues

https://www.paypal.com/webapps/mpp/security/secure-passwords

**Comment by duffn** [comment]
I'll update the screenshot for clarification, but the error seems to be for passwords > 20 characters.

**Comment by duffn** [comment]
I've added an updated screenshot. The error occurs when passwords > 20 characters.

https://github.com/duffn/dumb-password-rules/pull/32/commits/b7c99e23ec5573c5fc9dc925b59494da927604db
