### ISSUE TITLE
Please add https://www.labanquepostale.fr/

### ISSUE THREAD

**Issue by CyrilBrulebois** [duffn/dumb-password-rules#297]
La Banque Postale is a bank, authenticating with an account number and 6 digits (!)
→ https://www.labanquepostale.fr/

There's no obvious password policy page, one can only see a pad (right, you have to click, no password management either), and the “Validate” button changes colour when you have entered the 6th digit. Not sure what else I can share to document this delightful policy.

**Comment by CyrilBrulebois** [comment]
![pad](https://user-images.githubusercontent.com/8861145/69477346-703ded80-0de5-11ea-9048-c92b35924c6c.png)
Password input…

**Comment by duffn** [comment]
That’s a bad one. Feel free to open a PR for it. Thanks!
