### ISSUE TITLE
Add Google Cloud webassesor

### ISSUE THREAD

**Issue by duffn** [duffn/dumb-password-rules#302]
lol. 

<img width="742" alt="Screen Shot 2019-12-18 at 11 21 58 AM" src="https://user-images.githubusercontent.com/3457341/71116211-eb9a8100-2190-11ea-99ec-cbc8544b3099.png">

**Comment by iamkkushal** [comment]
Can you tell me how to reproduce this? I tried this but it looks like this is not valid now. Google seems to have fixed this.

**Comment by duffn** [comment]
Thanks. This is old, so perhaps it's been fixed.
