### ISSUE TITLE
Izly should not be included

### ISSUE THREAD

**Issue by ronangaillard** [duffn/dumb-password-rules#41]
No reason to include Izly here. 6 number pin is common and used in many bank websites. If you want to include Izly you should then include all (well most) bank websites.

About the fact that it is not translated in French maybe you should first try to learn how to use a web browser : 
<img width="643" alt="screen shot 2016-12-13 at 15 08 40" src="https://cloud.githubusercontent.com/assets/5607736/21143214/0b678e82-c146-11e6-84ad-675fd5457534.png">

About the fact that your account can be blocked after too many login failed attempts, that is the way every internet accounts work.

**Comment by nanoplink** [comment]
I think you didn't get my point. It may be not be clear in the pull request review and i apologize for that. I'll describe it here in more details.

N number pin is in fact common in bank websites. And in fact, it could not be that bad as a rule. The same applies to blocking account after a number of failed attempts.
However bank accounts give you a way much better login. That is, a login that is not predictable in an easy way. Izly is tied to your _university email account_ which is firstname.lastname@university.fr . If you were studying in the same university with me it would be ronan.gaillard@edu.univ-fcomte.fr . I already know half of the credentials to log in to your account. You can't except such a weak password rule with that.

As a reminder, at the launch of Izly there where no such account lock after a number of "failed" attempts. And input from the keyboard. Yup, you could guess the user password in (6^9) attempts with no restriction. What a design !

We are also talking about a service that is __REQUIRED__ for your daily student life. You can't eat if you can't use it. I can throw 3 log attempts with your address and now you're blocked and can't transfer money on your card.

Bonus point on the translation : I do indeed use an english locale on my system. Just display the whole site in my locale if available or don't even try to display anything but french. A "oh look i'm such in" website and service that is actually just plenty bullshit.

I reiterate, this website deserve its place here.

**Comment by nanoplink** [comment]
Anyway, it's to the owner of the repo to judge the pertinence of my entry. It was just a perfect moment to rant again about something that plenty sucks and piss a lot of students. It's not the end of the world if it is removed, all my points still applies :)

**Comment by duffn** [comment]
Is this 6 digit password for logging into the bank's website or for a PIN to use at an automated teller machine? 

I do not find it common in the US that a financial institution's website uses only a numerical PIN for logging into their online presence.

Here was a previous discussion on much the same topic: https://github.com/duffn/dumb-password-rules/pull/5#issuecomment-264917105

If this is the authentication for the website, I'm in favor of keeping it.

**Comment by ronangaillard** [comment]
> However bank accounts give you a way much better login. That is, a login that is not predictable in an easy way. 

Hummmmm.... It's easy to find the web account number of any bank (at least French banks as you seem to be located in France) so I don't think Izly is worse than any bank web login. If can find the login of any friend on its bank account using similar technics as doing the name.lastname@university.com. So I agree that this is weak, but then let's include any bank login style in this repo...

>Yup, you could guess the user password in (6^9) attempts with no restriction. What a design !
 Please do the math again... this is wrong... 

>We are also talking about a service that is REQUIRED for your daily student life. 
Any service for eating at university is required even if it is bad or good, and I guess this is not the subject of this repo... If you do not like it just try to change it rather than trying to criticise it, this won't lead you to anything good... No system is perfect... If you think you have a better system just show it off, explain it, rather than criticising the current one, this is too easy...

>Bonus point on the translation : I do indeed use an english locale on my system. 
That is why Izly is in English then... I don't understand why you are angry at it if you expect it to be in English and complain about the missing French translation...

I think Izly is a good system, it is hard to get good web interfaces for things like this at university. Of course it is not perfect but I think that if you want to be allowed to criticise it you should suggest another solution rather than just sit in your couch and criticize...

**Comment by nanoplink** [comment]
It's only for logging on their website.
