### ISSUE TITLE
Shame SAP AWS instance deployment wizard

### ISSUE THREAD

**Issue by lodotek** [duffn/dumb-password-rules#44]
See screenshot below:

![image](https://cloud.githubusercontent.com/assets/2421856/21276350/324b5e9e-c38e-11e6-9f94-ce32bb02acc9.png)

From https://cal.sap.com/

Sorry, short on time other wise I would have submitted a PR :-)

**Comment by duffn** [comment]
Thanks.

https://github.com/duffn/dumb-password-rules/pull/45
