### ISSUE TITLE
What's dumb about Parsec?

### ISSUE THREAD

**Issue by Steve-Tech** [duffn/dumb-password-rules#509]
I noticed Parsec is listed here with this:
> A service for screen sharing and enabling online multiplayer gaming, when the software itself only supports offline multiplayer.
>
> ![](https://raw.githubusercontent.com/duffn/dumb-password-rules/main/src/screenshots/parsec.png)

But the requirements in the image just simply mean it has to have at least 8 characters, not exactly 8 characters, and AFAIK there are no maximums.

Thought I might say I'm in no way affiliated with parsec, just used it before, and I'm not even sure I understand the message either. I'm happy to create a PR if I haven't missed anything.

**Comment by duffn** [comment]
Thanks for the note, please feel free to PR to update if the entry is incorrect.
