### ISSUE TITLE
Remove keypads from the list?

### ISSUE THREAD

**Issue by nlgranger** [duffn/dumb-password-rules#531]
I noticed the keypad from boursorama caused it to be included from the list.
AFAIK, it breaks the functionality of keyloggers, including physical ones.
It also discourages you to store your password on you computer by breaking password management tools. Although that may be annoying, I think there is an argument for it.
Finally, the password length is short, but 10^8 combinations (with bruteforce protection and 2FA) sounds all right for an authentication system.

Feel free to close, I don't really care about that bank's reputation, I just though it was odd to see it here.

**Comment by depperm** [comment]
it isn't necessarily a11y/508 compliant (accessible), for those who need screen readers. If you ignore the keypad the password is only 8 characters long.

**Comment by nlgranger** [comment]
Ah! I see the problem now. Thanks.
