### ISSUE TITLE
Amazing :)) ranked based on alexa

### ISSUE THREAD

**Issue by sahin** [duffn/dumb-password-rules#62]
Amazing, thank you to be a voice of my frustrations.

It will be so so cool, if u roughly ranked them also based on alexa ranking....

**Comment by duffn** [comment]
Thanks for the comment. I feel like that would be difficult to maintain and possibly a barrier for contributors? I'd like to keep it as simple as possible for new people coming to the repository. Thoughts?

**Comment by sahin** [comment]
@duffn You are right, u can keep the readme as is. but create a new wiki for top 100 web sites. (which they dont change a lot). 

so I have a feeling many people will add to the both.

**Comment by duffn** [comment]
I think I will keep this repo as is for now, with just an ever growing list of any and all sites that people would like to submit.
