### ISSUE TITLE
Remove OVH

### ISSUE THREAD

**Issue by awwright** [duffn/dumb-password-rules#64]
The OVH 2FA example is using a numerical input field `<input type="number"/>` which automatically causes some (but not all) browsers to include the lamented increment/decrement buttons.

2FA algorithms that use numbers are common (standardized in RFC 6238) and it makes sense to use `type="number"` in these cases (for example, this will show a numerical keyboard on phones instead of a QWERTY keyboard).

So OVH is doing 2FA exactly right and should be removed from the list.

**Comment by duffn** [comment]
Thanks for the note. Can you submit a PR to remove the entry?

**Comment by duffn** [comment]
Fixed in https://github.com/duffn/dumb-password-rules/pull/65#pullrequestreview-45885887
