### ISSUE TITLE
Add Singapore Airlines

### ISSUE THREAD

**Issue by zbjornson** [duffn/dumb-password-rules#7]
Requires `/\d{6}/` (6-digit numeric).

![img_20161205_082526](https://cloud.githubusercontent.com/assets/469365/20892813/720352f8-bac4-11e6-83e8-251981ab591e.jpg)

**Comment by duffn** [comment]
Is this a legitimate registration password for the site or is this an additional PIN number?

**Comment by zbjornson** [comment]
It's the sole password, not a supplement.

(Sorry for not making a PR, am on mobile for a while.)

**Comment by duffn** [comment]
Ouch, that's a bad one. Thanks.
