### ISSUE TITLE
offensive language discovered in the last name field

### ISSUE THREAD

**Issue by nicolasdanelon** [duffn/dumb-password-rules#99]
![image](https://user-images.githubusercontent.com/2846046/44853851-6c043e00-ac3d-11e8-90a4-ca59dad2e08f.png)

sauce : https://twitter.com/natalieweiner/status/1034533245839450113?s=19

**Comment by duffn** [comment]
Oh, that's a beauty. If you want to submit a PR, it would be much appreciated.

**Comment by nicolasdanelon** [comment]
but... I don't know the website... what title should I use?

**Comment by duffn** [comment]
It looks like it's this (http://www.maxpreps.com/) according to the OP (https://twitter.com/natalieweiner/status/1034533630071193602)

**Comment by nicolasdanelon** [comment]
@duffn can you check my fork? I can't link the image :P

**Comment by duffn** [comment]
Close. You need to actually add the image to the `screenshots` directory and then add a line for it at the very bottom of the file as well.

```
`BMW ConnectedDrive <https://www.bmw-connecteddrive.co.uk/>`__
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Although the prompt suggests good things, after many failed attempts to
set a new password, it turns out you can ONLY use the special characters
shown in the prompt

|BMW ConnectedDrive|
```

Then at the bottom, you'll see a bunch of lines that look like this:

```
.. |BMO Bank of Montreal| image:: /screenshots/bmo.png
.. |BMW ConnectedDrive| image:: /screenshots/bmw-connected.PNG
.. |California DMV| image:: /screenshots/ca-dmv.png
```

**Comment by nicolasdanelon** [comment]
closing by #100
